<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
	    <link rel="stylesheet" href="css/style.css"/>
        <link rel="stylesheet" href="css/sidemenu.css"/>
        <link rel="stylesheet" href="css/box-container.css"/>
        <link rel="stylesheet" href="css/bootstrap.min.css">


        <title>Navigatte</title> 
        <style>
            #side-menu {
                /*background: linear-gradient(<?php //echo $gradientString ?>);*/
            }

            .user-img {
                background-image: url("<?php htmlout('img/' . $userInfo['profile_pic']); ?>");
            }
        </style>
	</head>

	<body>
        <svg class="svg-container">
            <rect id="node-container-mouse-area">
            </rect>
        </svg>

        <!--Side menu-->
        <nav id="side-menu">   
            <a href="." id="logo">Navigatte</a>

            <input name="search" id="search-field" type="text" placeholder="Search..." />

            <div class="divisor"></div>  

            <div class="user-navigation">
                <button id="createNodeButton" class="btn btn-info btn-lg" 
                    type="button" 
                    style="height:50px;width:300px;border-radius:0;position:absolute;left:0; top:180px;">
                    Create New Node
                </button>

                <button id="saveChangesButton" class="btn btn-success btn-lg" 
                    type="button" 
                    style="height:50px;width:300px;border-radius:0;position:absolute;left:0; top:250px;" 
                    onclick="Navigatte.Changes.Save();">
                    Save Changes
                </button>
            </div>

            <div class="search-results" style="display:none"></div>

            <!--<div id="user-profile-container">
                <div class="user-img"></div>
                <div id="user-name" class="black-font"><?php htmlout($userInfo['screen_name']); ?></div>
                <div id="user-trackers" class="black-font">Trackers 1000</div>
                <div id="user-tracking" class="black-font">Tracking 1000</div>
                <div id="user-description" class="black-font"><?php htmlout($userInfo['screen_description']); ?></div>
            </div>
            <div id="search-results-container"></div>-->

            <footer>
                <div id="pta" class="black-font">Privacy | Terms | About</div>
                <div id="copyright" class="black-font">Copyright 2015 - Navigatte</div>
            </footer>
        </nav>

        <!--General Content - Generated by PHP-->
        <section id="general-content" ng-controller="ContentController">
            <div class="btn-group" style="position:absolute;top:5px;right:5px;">
                <button type="button" 
                        class="btn btn-default dropdown-toggle btn-primary btn-lg" 
                        data-toggle="dropdown" 
                        aria-haspopup="true" 
                        aria-expanded="false"> 
                        <?php htmlout($userInfo['screen_name']); ?> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="http://localhost/projects/navigatte/?user=<?php htmlout($userInfo['page_name']); ?>">Profile</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="javascript:void(0)" onclick="document.getElementById('signOutForm').submit();">Sign Out</a></li>
                    <form method="post" id="signOutForm"><input type="hidden" name="action" value="signout"></form>
                </ul>
            </div>
            <div class="navi-content-window">
                <div class="navi-content-close-button">x</div>
                <div class="navi-content-data"></div>
            </div>
        </section>
        
        <script src="js/jquery-2.1.4.min.js"></script>
        <script src="js/eventhandler.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="https://cdn.rawgit.com/alertifyjs/alertify.js/v1.0.5/dist/js/alertify.js"></script>
        <script>
            alertify.logPosition("bottom right");
            alertify.maxLogItems(10);
        </script>
		<script src="js/d3.v3.min.js"></script>
        <script src="js/g-query.js"></script>
        <script src="js/grow-modal.js"></script>

        <script src="navigatte/navigatte.js"></script>
        <script src="navigatte/navigatte-container.js"></script>
        <script src="navigatte/navigatte-nodes.js"></script>
        <script src="navigatte/navigatte-links.js"></script>
        <script src="navigatte/navigatte-select.js"></script>
        <script src="navigatte/navigatte-content-modal.js"></script>
        <script src="navigatte/navigatte-changes.js"></script>
        <script src="navigatte/navigatte-changes-node.js"></script>
        <script src="navigatte/navigatte-create-modal.js"></script>
        <script src="navigatte/navigatte-create-links.js"></script>
        <script src="navigatte/navigatte-changes-link.js"></script>
        <script src="navigatte/navigatte-search.js"></script>
        <script src="navigatte/navigatte-keyactions.js"></script>
        <script src="navigatte/navigatte-content.js"></script>
        <script src="navigatte/navigatte-node-finder.js"></script>

        <script src="app.js"></script>
        <script>
            var pageName = '<?php htmlout($userInfo['page_name']); ?>';

            initApp(pageName);

            $("#createNodeButton").click(Navigatte.CreateModal.Open);

        </script>
		<!--<script type="text/javascript" src="main.js"></script>-->
	</body>
</html>