<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
        <link rel="stylesheet" href="css/style.css"/>
        <link rel="stylesheet" href="css/sidemenu.css"/>
        <link rel="stylesheet" href="css/box-container.css"/>
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <title>Navigatte - <?php htmlout($userinfo['screen_name']); ?></title>        
        <style>
            #side-menu {
                /*background: linear-gradient(<?php //echo $gradientString ?>);*/
            }

            .user-img {
                background-image: url("<?php htmlout('img/' . $userinfo['profile_pic']); ?>");
            }
        </style>
	</head>

	<body>
        <svg class="svg-container">
            <rect id="node-container-mouse-area">
            </rect>
        </svg>

        <!--Side menu-->
        <nav id="side-menu">   
            <a href="." id="logo">Navigatte</a>

            <input name="search" id="search-field" type="text" placeholder="Pesquisar..." />

            <div class="divisor"></div> 

            <div class="user-navigation">

                <div id="user-profile-container">
                    <div class="user-img"></div>
                    <div id="user-name" class="black-font"><?php htmlout($userinfo['screen_name']); ?></div>
                    <div id="user-trackers" class="black-font">Trackers 1000</div>
                    <div id="user-tracking" class="black-font">Tracking 1000</div>
                    <div id="user-description" class="black-font"><?php htmlout($userinfo['screen_description']); ?></div>
                </div>

            </div>

            <div class="search-results" style="display:none"></div>

            <!--<div id="user-profile-container">
                <div class="user-img"></div>
                <div id="user-name" class="black-font"><?php htmlout($userInfo['screen_name']); ?></div>
                <div id="user-trackers" class="black-font">Trackers 1000</div>
                <div id="user-tracking" class="black-font">Tracking 1000</div>
                <div id="user-description" class="black-font"><?php htmlout($userInfo['screen_description']); ?></div>
            </div>
            <div id="search-results-container"></div>-->

            <footer>
                <div id="pta" class="black-font">Privacy | Terms | About</div>
                <div id="copyright" class="black-font">Copyright 2015 - Navigatte</div>
            </footer>
        </nav>

        <!--General Content - Generated by PHP-->
        <section id="general-content">
            <div class="navi-content-window">
                <div class="navi-content-close-button">x</div>
                <div class="navi-content-data"></div>
            </div>
            <!--<div class="button-save"">Save Positions</div>-->
        </section>
        <script src="js/jquery-2.1.4.min.js"></script>
        <script src="js/eventhandler.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="https://cdn.rawgit.com/alertifyjs/alertify.js/v1.0.5/dist/js/alertify.js"></script>
        <script>
            alertify.logPosition("bottom right");
            alertify.maxLogItems(10);
        </script>
        <script src="js/d3.v3.min.js"></script>
        <script src="js/g-query.js"></script>
        <script src="js/grow-modal.js"></script>

        <script src="navigatte/navigatte.js"></script>
        <script src="navigatte/navigatte-container.js"></script>
        <script src="navigatte/navigatte-nodes.js"></script>
        <script src="navigatte/navigatte-links.js"></script>
        <script src="navigatte/navigatte-select.js"></script>
        <script src="navigatte/navigatte-content.js"></script>
        <script src="navigatte/navigatte-content-modal.js"></script>
        <script src="navigatte/navigatte-node-finder.js"></script>
        <script src="navigatte/navigatte-project.js"></script>

        <script src="app.js"></script>
        <script>    
            var pageName = '<?php htmlout($username); ?>';
            initApp(pageName);
        </script>
	</body>
</html>